### ISSUE TITLE
Compatibility issue (Intellij IDEA 2024.3/#IU-243.*)

### ISSUE THREAD

**Issue by Jorgenssen** [mohamead/allure-report-plugin#49]
Hello,
Since new version Intellij IDEA 2024.3/#IU-243.* is available, the plugin is not available to use due to incompatibility
<img width="751" alt="image" src="https://github.com/user-attachments/assets/f88de365-83f5-41b8-9129-5f7ed8779b52">

---
P.S. I can try to take a look on my own, but later

**Comment by mohamead** [comment]
Hi @Jorgenssen. Thx for the issue. I will have a look at it asap :)
