### ISSUE TITLE
I want to see the Behaviour tab when I open Allure report locally. Is that possible with this plugin?

### ISSUE THREAD

**Issue by PrakratiAgarwal123** [mohamead/allure-report-plugin#51]
I want to see the Behaviour tab when I open Allure report locally. Is that possible with this plugin?
<img width="125" alt="image" src="https://github.com/user-attachments/assets/1f4ca3e5-84be-4eb0-b715-d816b7a41f3f">

**Comment by mohamead** [comment]
Hi. Thx for the issue, and sorry for a late reply. I will have a look at this asap!

**Comment by mohamead** [comment]
Version [0.0.7](https://plugins.jetbrains.com/plugin/24074-allure-report/versions) is available. Closing this ticket.
